# Generated by Django 2.1.5 on 2019-01-13 04:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import stdimage.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PerfilUsuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direccion', models.TextField(blank=True, max_length=100)),
                ('telefono', models.CharField(blank=True, max_length=20)),
                ('tipo_usuario', models.PositiveSmallIntegerField(choices=[(0, 'Personal'), (1, 'Paciente')], default=1)),
                ('avatar', stdimage.models.StdImageField(default='usuarios/avatar.png', upload_to='usuarios/%Y/%m/')),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
