# Generated by Django 2.1.5 on 2019-01-14 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitio', '0002_auto_20190113_2345'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cita',
            name='dia_hora_agendado',
        ),
        migrations.AddField(
            model_name='cita',
            name='dia_agendado',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cita',
            name='hora_agendado',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
