# Generated by Django 2.1.5 on 2019-01-31 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitio', '0004_cita_observacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cita',
            name='observacion',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
