# Generated by Django 2.1.5 on 2019-03-25 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitio', '0006_auto_20190130_2147'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cita',
            name='dia_agendado',
            field=models.DateField(db_index=True, null=True),
        ),
    ]
